using System;
using UnityEngine;

namespace com.ootii.Actors.AnimationControllers
{
	// Token: 0x020000F1 RID: 241
	[MotionName("Basic Idle Arms")]
	[MotionDescription("Manages the posing of the arms. Meant to be on the Arms Only Layer.")]
	public class BasicIdleArms : MotionControllerMotion
	{
		// Token: 0x1700038B RID: 907
		// (get) Token: 0x06000CE8 RID: 3304 RVA: 0x0003FE41 File Offset: 0x0003E041
		// (set) Token: 0x06000CE9 RID: 3305 RVA: 0x0003FE4C File Offset: 0x0003E04C
		public string RequiredForms
		{
			get
			{
				return this._RequiredForms;
			}
			set
			{
				this._RequiredForms = value;
				if (Application.isPlaying)
				{
					this.mRequiredForms = null;
					if (this._RequiredForms.Length > 0)
					{
						string[] array = this._RequiredForms.Split(',', StringSplitOptions.None);
						this.mRequiredForms = new int[array.Length];
						for (int i = 0; i < array.Length; i++)
						{
							this.mRequiredForms[i] = -1;
							int.TryParse(array[i], out this.mRequiredForms[i]);
						}
					}
				}
			}
		}

		// Token: 0x1700038C RID: 908
		// (get) Token: 0x06000CEA RID: 3306 RVA: 0x0003FEC5 File Offset: 0x0003E0C5
		public override bool VerifyTransition
		{
			get
			{
				return false;
			}
		}

		// Token: 0x06000CEB RID: 3307 RVA: 0x0003FEC8 File Offset: 0x0003E0C8
		public BasicIdleArms()
		{
		}

		// Token: 0x06000CEC RID: 3308 RVA: 0x0003FF18 File Offset: 0x0003E118
		public BasicIdleArms(MotionController rController)
			: base(rController)
		{
		}

		// Token: 0x06000CED RID: 3309 RVA: 0x0003FF69 File Offset: 0x0003E169
		public override void Awake()
		{
			base.Awake();
			this.RequiredForms = this._RequiredForms;
		}

		// Token: 0x06000CEE RID: 3310 RVA: 0x0003FF80 File Offset: 0x0003E180
		public bool TestActivate(int rForm)
		{
			bool flag = this.mRequiredForms == null;
			if (!flag)
			{
				for (int i = 0; i < this.mRequiredForms.Length; i++)
				{
					if (this.mRequiredForms[i] == rForm)
					{
						flag = true;
						break;
					}
				}
			}
			return flag;
		}

		// Token: 0x06000CEF RID: 3311 RVA: 0x0003FFC0 File Offset: 0x0003E1C0
		public override bool TestUpdate()
		{
			if (this.mRequiredForms != null)
			{
				int currentForm = this.mMotionController.CurrentForm;
				for (int i = 0; i < this.mRequiredForms.Length; i++)
				{
					if (this.mRequiredForms[i] == currentForm)
					{
						return true;
					}
				}
				return false;
			}
			return true;
		}

		// Token: 0x06000CF0 RID: 3312 RVA: 0x00040004 File Offset: 0x0003E204
		public override bool Activate(MotionControllerMotion rPrevMotion)
		{
			this.mActiveForm = ((this._Form >= 0) ? this._Form : this.mMotionController.CurrentForm);
			this.mMotionController.SetAnimatorMotionPhase(this.mMotionLayer.AnimatorLayerIndex, this.PHASE_START, this.mActiveForm, 0, true);
			return base.Activate(rPrevMotion);
		}

		// Token: 0x1700038D RID: 909
		// (get) Token: 0x06000CF1 RID: 3313 RVA: 0x0004005E File Offset: 0x0003E25E
		public override bool HasAutoGeneratedCode
		{
			get
			{
				return true;
			}
		}

		// Token: 0x1700038E RID: 910
		// (get) Token: 0x06000CF2 RID: 3314 RVA: 0x00040064 File Offset: 0x0003E264
		public override bool IsInMotionState
		{
			get
			{
				int animatorStateID = this.mMotionLayer._AnimatorStateID;
				int animatorTransitionID = this.mMotionLayer._AnimatorTransitionID;
				if (animatorTransitionID == 0)
				{
					if (animatorStateID == this.STATE_Empty)
					{
						return true;
					}
					if (animatorStateID == this.STATE_UnarmedIdlePose)
					{
						return true;
					}
				}
				return animatorTransitionID == this.TRANS_AnyState_UnarmedIdlePose || animatorTransitionID == this.TRANS_EntryState_UnarmedIdlePose;
			}
		}

		// Token: 0x06000CF3 RID: 3315 RVA: 0x000400B9 File Offset: 0x0003E2B9
		public override bool IsMotionState(int rStateID)
		{
			return rStateID == this.STATE_Empty || rStateID == this.STATE_UnarmedIdlePose;
		}

		// Token: 0x06000CF4 RID: 3316 RVA: 0x000400D2 File Offset: 0x0003E2D2
		public override bool IsMotionState(int rStateID, int rTransitionID)
		{
			if (rTransitionID == 0)
			{
				if (rStateID == this.STATE_Empty)
				{
					return true;
				}
				if (rStateID == this.STATE_UnarmedIdlePose)
				{
					return true;
				}
			}
			return rTransitionID == this.TRANS_AnyState_UnarmedIdlePose || rTransitionID == this.TRANS_EntryState_UnarmedIdlePose;
		}

		// Token: 0x06000CF5 RID: 3317 RVA: 0x00040104 File Offset: 0x0003E304
		public override void LoadAnimatorData()
		{
			string layerName = this.mMotionController.Animator.GetLayerName(this.mMotionLayer._AnimatorLayerIndex);
			this.TRANS_AnyState_UnarmedIdlePose = this.mMotionController.AddAnimatorName("AnyState -> " + layerName + ".BasicIdleArms-SM.Unarmed Idle Pose");
			this.TRANS_EntryState_UnarmedIdlePose = this.mMotionController.AddAnimatorName("Entry -> " + layerName + ".BasicIdleArms-SM.Unarmed Idle Pose");
			this.STATE_Empty = this.mMotionController.AddAnimatorName(layerName + ".Empty");
			this.STATE_UnarmedIdlePose = this.mMotionController.AddAnimatorName(layerName + ".BasicIdleArms-SM.Unarmed Idle Pose");
		}

		// Token: 0x0400071E RID: 1822
		public int PHASE_UNKNOWN;

		// Token: 0x0400071F RID: 1823
		public int PHASE_START = 3650;

		// Token: 0x04000720 RID: 1824
		public int PHASE_STOP = 3610;

		// Token: 0x04000721 RID: 1825
		public string _RequiredForms = "500,550";

		// Token: 0x04000722 RID: 1826
		protected int mActiveForm;

		// Token: 0x04000723 RID: 1827
		protected int[] mRequiredForms;

		// Token: 0x04000724 RID: 1828
		public int STATE_Empty = -1;

		// Token: 0x04000725 RID: 1829
		public int STATE_UnarmedIdlePose = -1;

		// Token: 0x04000726 RID: 1830
		public int TRANS_AnyState_UnarmedIdlePose = -1;

		// Token: 0x04000727 RID: 1831
		public int TRANS_EntryState_UnarmedIdlePose = -1;
	}
}
