using System;
using UnityEngine;

namespace com.ootii.Actors.AnimationControllers
{
	// Token: 0x02000100 RID: 256
	[MotionName("Empty")]
	[MotionDescription("Used on additional layers as the 'empty' motion to clear out any animation so that the base layer can be full-body.")]
	public class Empty : MotionControllerMotion
	{
		// Token: 0x06000ED7 RID: 3799 RVA: 0x0004D660 File Offset: 0x0004B860
		public Empty()
		{
			this._Category = 1;
			this._Priority = 0f;
			this._Form = 0;
		}

		// Token: 0x06000ED8 RID: 3800 RVA: 0x0004D6B4 File Offset: 0x0004B8B4
		public Empty(MotionController rController)
			: base(rController)
		{
			this._Category = 1;
			this._Priority = 0f;
			this._Form = 0;
		}

		// Token: 0x06000ED9 RID: 3801 RVA: 0x0004D708 File Offset: 0x0004B908
		public override void Awake()
		{
			base.Awake();
		}

		// Token: 0x06000EDA RID: 3802 RVA: 0x0004D710 File Offset: 0x0004B910
		public override bool TestActivate()
		{
			return this.mMotionLayer.ActiveMotion == null || (this.mIsStartable && this.mMotionController.IsGrounded && this.mMotionController.State.InputMagnitudeTrend.Average == 0f);
		}

		// Token: 0x06000EDB RID: 3803 RVA: 0x0004D764 File Offset: 0x0004B964
		public override bool TestUpdate()
		{
			return !this.mIsAnimatorActive || this.IsInMotionState;
		}

		// Token: 0x06000EDC RID: 3804 RVA: 0x0004D779 File Offset: 0x0004B979
		public override bool Activate(MotionControllerMotion rPrevMotion)
		{
			this.mMotionController.SetAnimatorMotionPhase(this.mMotionLayer.AnimatorLayerIndex, this.PHASE_START, this._Form, this.mParameter, true);
			return base.Activate(rPrevMotion);
		}

		// Token: 0x06000EDD RID: 3805 RVA: 0x0004D7AB File Offset: 0x0004B9AB
		public override void Deactivate()
		{
			base.Deactivate();
		}

		// Token: 0x06000EDE RID: 3806 RVA: 0x0004D7B3 File Offset: 0x0004B9B3
		public override void UpdateRootMotion(float rDeltaTime, int rUpdateIndex, ref Vector3 rMovement, ref Quaternion rRotation)
		{
			rMovement = Vector3.zero;
			rRotation = Quaternion.identity;
		}

		// Token: 0x06000EDF RID: 3807 RVA: 0x0004D7CC File Offset: 0x0004B9CC
		public override void Update(float rDeltaTime, int rUpdateIndex)
		{
		}

		// Token: 0x06000EE0 RID: 3808 RVA: 0x0004D7CE File Offset: 0x0004B9CE
		public static string GroupName()
		{
			return "Basic";
		}

		// Token: 0x17000429 RID: 1065
		// (get) Token: 0x06000EE1 RID: 3809 RVA: 0x0004D7D5 File Offset: 0x0004B9D5
		public override bool HasAutoGeneratedCode
		{
			get
			{
				return true;
			}
		}

		// Token: 0x1700042A RID: 1066
		// (get) Token: 0x06000EE2 RID: 3810 RVA: 0x0004D7D8 File Offset: 0x0004B9D8
		public override bool IsInMotionState
		{
			get
			{
				int animatorStateID = this.mMotionLayer._AnimatorStateID;
				int animatorTransitionID = this.mMotionLayer._AnimatorTransitionID;
				if (animatorTransitionID == 0)
				{
					if (animatorStateID == this.STATE_Empty)
					{
						return true;
					}
					if (animatorStateID == this.STATE_EmptyPose)
					{
						return true;
					}
				}
				return animatorTransitionID == this.TRANS_AnyState_EmptyPose || animatorTransitionID == this.TRANS_EntryState_EmptyPose || animatorTransitionID == this.TRANS_AnyState_EmptyPose || animatorTransitionID == this.TRANS_EntryState_EmptyPose;
			}
		}

		// Token: 0x06000EE3 RID: 3811 RVA: 0x0004D843 File Offset: 0x0004BA43
		public override bool IsMotionState(int rStateID)
		{
			return rStateID == this.STATE_Empty || rStateID == this.STATE_EmptyPose;
		}

		// Token: 0x06000EE4 RID: 3812 RVA: 0x0004D85C File Offset: 0x0004BA5C
		public override bool IsMotionState(int rStateID, int rTransitionID)
		{
			if (rTransitionID == 0)
			{
				if (rStateID == this.STATE_Empty)
				{
					return true;
				}
				if (rStateID == this.STATE_EmptyPose)
				{
					return true;
				}
			}
			return rTransitionID == this.TRANS_AnyState_EmptyPose || rTransitionID == this.TRANS_EntryState_EmptyPose || rTransitionID == this.TRANS_AnyState_EmptyPose || rTransitionID == this.TRANS_EntryState_EmptyPose;
		}

		// Token: 0x06000EE5 RID: 3813 RVA: 0x0004D8B0 File Offset: 0x0004BAB0
		public override void LoadAnimatorData()
		{
			string layerName = this.mMotionController.Animator.GetLayerName(this.mMotionLayer._AnimatorLayerIndex);
			this.TRANS_AnyState_EmptyPose = this.mMotionController.AddAnimatorName("AnyState -> " + layerName + ".Empty-SM.EmptyPose");
			this.TRANS_EntryState_EmptyPose = this.mMotionController.AddAnimatorName("Entry -> " + layerName + ".Empty-SM.EmptyPose");
			this.TRANS_AnyState_EmptyPose = this.mMotionController.AddAnimatorName("AnyState -> " + layerName + ".Empty-SM.EmptyPose");
			this.TRANS_EntryState_EmptyPose = this.mMotionController.AddAnimatorName("Entry -> " + layerName + ".Empty-SM.EmptyPose");
			this.STATE_Empty = this.mMotionController.AddAnimatorName(layerName + ".Empty");
			this.STATE_EmptyPose = this.mMotionController.AddAnimatorName(layerName + ".Empty-SM.EmptyPose");
		}

		// Token: 0x04000906 RID: 2310
		public int PHASE_UNKNOWN;

		// Token: 0x04000907 RID: 2311
		public int PHASE_START = 3010;

		// Token: 0x04000908 RID: 2312
		public int STATE_Empty = -1;

		// Token: 0x04000909 RID: 2313
		public int STATE_EmptyPose = -1;

		// Token: 0x0400090A RID: 2314
		public int TRANS_AnyState_EmptyPose = -1;

		// Token: 0x0400090B RID: 2315
		public int TRANS_EntryState_EmptyPose = -1;
	}
}
