using System;

namespace com.ootii.Actors.AnimationControllers
{
	// Token: 0x0200010C RID: 268
	[MotionName("Punch")]
	[MotionDescription("A simple motion used to test motions on different layers. When put on a seperate layer, this motion will cause the avatar to punch with his left hand.")]
	public class Punch : MotionControllerMotion
	{
		// Token: 0x17000466 RID: 1126
		// (get) Token: 0x06000FBC RID: 4028 RVA: 0x00052D43 File Offset: 0x00050F43
		public override bool VerifyTransition
		{
			get
			{
				return false;
			}
		}

		// Token: 0x06000FBD RID: 4029 RVA: 0x00052D46 File Offset: 0x00050F46
		public Punch()
		{
			this._Priority = 10f;
			this._ActionAlias = "Fire1";
			this.mIsStartable = true;
		}

		// Token: 0x06000FBE RID: 4030 RVA: 0x00052D6B File Offset: 0x00050F6B
		public Punch(MotionController rController)
			: base(rController)
		{
			this._Priority = 10f;
			this._ActionAlias = "Fire1";
			this.mIsStartable = true;
		}

		// Token: 0x06000FBF RID: 4031 RVA: 0x00052D91 File Offset: 0x00050F91
		public override bool TestActivate()
		{
			return this.mMotionController._InputSource != null && this._ActionAlias.Length > 0 && this.mMotionController._InputSource.IsJustPressed(this._ActionAlias);
		}

		// Token: 0x06000FC0 RID: 4032 RVA: 0x00052DCC File Offset: 0x00050FCC
		public override bool TestUpdate()
		{
			return this.mIsActivatedFrame || ((!this.mIsAnimatorActive || this.IsInMotionState) && (!this.mIsAnimatorActive || this.mMotionLayer._AnimatorStateID != Punch.STATE_Punch || this.mMotionLayer._AnimatorStateNormalizedTime <= 0.8f));
		}

		// Token: 0x06000FC1 RID: 4033 RVA: 0x00052E24 File Offset: 0x00051024
		public override bool Activate(MotionControllerMotion rPrevMotion)
		{
			this.mMotionController.SetAnimatorMotionPhase(this.mMotionLayer._AnimatorLayerIndex, 500, true);
			return base.Activate(rPrevMotion);
		}

		// Token: 0x17000467 RID: 1127
		// (get) Token: 0x06000FC2 RID: 4034 RVA: 0x00052E49 File Offset: 0x00051049
		public override bool HasAutoGeneratedCode
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000468 RID: 1128
		// (get) Token: 0x06000FC3 RID: 4035 RVA: 0x00052E4C File Offset: 0x0005104C
		public override bool IsInMotionState
		{
			get
			{
				int animatorStateID = this.mMotionLayer._AnimatorStateID;
				int animatorTransitionID = this.mMotionLayer._AnimatorTransitionID;
				if (animatorTransitionID == 0)
				{
					if (animatorStateID == Punch.STATE_Empty)
					{
						return true;
					}
					if (animatorStateID == Punch.STATE_Punch)
					{
						return true;
					}
				}
				return animatorTransitionID == Punch.TRANS_AnyState_Punch || animatorTransitionID == Punch.TRANS_EntryState_Punch || animatorTransitionID == Punch.TRANS_Punch_Empty;
			}
		}

		// Token: 0x06000FC4 RID: 4036 RVA: 0x00052EA7 File Offset: 0x000510A7
		public override bool IsMotionState(int rStateID)
		{
			return rStateID == Punch.STATE_Empty || rStateID == Punch.STATE_Punch;
		}

		// Token: 0x06000FC5 RID: 4037 RVA: 0x00052EBE File Offset: 0x000510BE
		public override bool IsMotionState(int rStateID, int rTransitionID)
		{
			if (rTransitionID == 0)
			{
				if (rStateID == Punch.STATE_Empty)
				{
					return true;
				}
				if (rStateID == Punch.STATE_Punch)
				{
					return true;
				}
			}
			return rTransitionID == Punch.TRANS_AnyState_Punch || rTransitionID == Punch.TRANS_EntryState_Punch || rTransitionID == Punch.TRANS_Punch_Empty;
		}

		// Token: 0x06000FC6 RID: 4038 RVA: 0x00052EF8 File Offset: 0x000510F8
		public override void LoadAnimatorData()
		{
			string layerName = this.mMotionController.Animator.GetLayerName(0);
			string layerName2 = this.mMotionController.Animator.GetLayerName(this.mMotionLayer._AnimatorLayerIndex);
			Punch.TRANS_AnyState_Punch = this.mMotionController.AddAnimatorName("AnyState -> " + layerName2 + ".Punch-SM.Punch");
			Punch.TRANS_EntryState_Punch = this.mMotionController.AddAnimatorName("Entry -> " + layerName2 + ".Punch-SM.Punch");
			Punch.STATE_Empty = this.mMotionController.AddAnimatorName(layerName + ".Empty");
			Punch.STATE_Punch = this.mMotionController.AddAnimatorName(layerName2 + ".Punch-SM.Punch");
			Punch.TRANS_Punch_Empty = this.mMotionController.AddAnimatorName(layerName2 + ".Punch-SM.Punch -> " + layerName + ".Empty");
		}

		// Token: 0x04000A19 RID: 2585
		public const int PHASE_UNKNOWN = 0;

		// Token: 0x04000A1A RID: 2586
		public const int PHASE_START = 500;

		// Token: 0x04000A1B RID: 2587
		public static int STATE_Empty = -1;

		// Token: 0x04000A1C RID: 2588
		public static int STATE_Punch = -1;

		// Token: 0x04000A1D RID: 2589
		public static int TRANS_AnyState_Punch = -1;

		// Token: 0x04000A1E RID: 2590
		public static int TRANS_EntryState_Punch = -1;

		// Token: 0x04000A1F RID: 2591
		public static int TRANS_Punch_Empty = -1;
	}
}
