using System;
using com.ootii.Actors.AnimationControllers;
using com.ootii.Actors.Combat;
using com.ootii.Geometry;
using com.ootii.Messages;
using UnityEngine;

namespace com.ootii.MotionControllerPacks
{
	// Token: 0x02000008 RID: 8
	[MotionName("Death")]
	[MotionDescription("Support generic animations for dying.")]
	public class Death : MotionControllerMotion
	{
		// Token: 0x0600007A RID: 122 RVA: 0x00004A4B File Offset: 0x00002C4B
		public Death()
		{
			this._Pack = Idle.GroupName();
			this._Category = 9;
			this._Priority = 100f;
			this._ActionAlias = "";
			this._OverrideLayers = true;
		}

		// Token: 0x0600007B RID: 123 RVA: 0x00004A83 File Offset: 0x00002C83
		public Death(MotionController rController)
			: base(rController)
		{
			this._Pack = Idle.GroupName();
			this._Category = 9;
			this._Priority = 100f;
			this._ActionAlias = "";
		}

		// Token: 0x0600007C RID: 124 RVA: 0x00004AB5 File Offset: 0x00002CB5
		public override void Awake()
		{
			base.Awake();
		}

		// Token: 0x0600007D RID: 125 RVA: 0x00004AC0 File Offset: 0x00002CC0
		public override bool TestActivate()
		{
			return this.mIsStartable && this.mMotionController.IsGrounded && this.mActorController.State.Stance == 0 && (this._ActionAlias.Length > 0 && this.mMotionController._InputSource != null && this.mMotionController._InputSource.IsJustPressed(this._ActionAlias));
		}

		// Token: 0x0600007E RID: 126 RVA: 0x00004B30 File Offset: 0x00002D30
		public override bool TestUpdate()
		{
			return true;
		}

		// Token: 0x0600007F RID: 127 RVA: 0x00004B33 File Offset: 0x00002D33
		public override bool TestInterruption(MotionControllerMotion rMotion)
		{
			return false;
		}

		// Token: 0x06000080 RID: 128 RVA: 0x00004B36 File Offset: 0x00002D36
		public override bool Activate(MotionControllerMotion rPrevMotion)
		{
			this.mIsClean = false;
			this.mActorController.AllowPushback = true;
			this.mMotionController.SetAnimatorMotionPhase(this.mMotionLayer._AnimatorLayerIndex, 1840, 180, false);
			return base.Activate(rPrevMotion);
		}

		// Token: 0x06000081 RID: 129 RVA: 0x00004B73 File Offset: 0x00002D73
		public override void Deactivate()
		{
			base.Deactivate();
		}

		// Token: 0x06000082 RID: 130 RVA: 0x00004B7B File Offset: 0x00002D7B
		public override void UpdateRootMotion(float rDeltaTime, int rUpdateIndex, ref Vector3 rMovement, ref Quaternion rRotation)
		{
		}

		// Token: 0x06000083 RID: 131 RVA: 0x00004B80 File Offset: 0x00002D80
		public override void Update(float rDeltaTime, int rUpdateIndex)
		{
			if (this.mMotionLayer._AnimatorTransitionID == Death.TRANS_EntryState_Death_0 || this.mMotionLayer._AnimatorTransitionID == Death.TRANS_EntryState_Death_180)
			{
				this.mMotionController.SetAnimatorMotionPhase(this.mMotionLayer._AnimatorLayerIndex, 0, 0, true);
			}
			if ((this.mMotionLayer._AnimatorStateID == Death.STATE_Death_0 || this.mMotionLayer._AnimatorStateID == Death.STATE_Death_180) && !this.mIsClean && this.mMotionLayer._AnimatorStateNormalizedTime > 0.6f)
			{
				this.mIsClean = true;
				this.mActorController.AllowPushback = false;
				this.mActorController.RemoveBodyShapes();
			}
		}

		// Token: 0x06000084 RID: 132 RVA: 0x00004C28 File Offset: 0x00002E28
		public override void OnMessageReceived(IMessage rMessage)
		{
			if (this.mIsActive)
			{
				return;
			}
			if (rMessage == null)
			{
				return;
			}
			if (rMessage.IsHandled)
			{
				return;
			}
			if (this.mActorController.State.Stance != 0)
			{
				return;
			}
			if (rMessage is CombatMessage)
			{
				CombatMessage combatMessage = rMessage as CombatMessage;
				if (!(combatMessage.Attacker == this.mMotionController.gameObject) && combatMessage.Defender == this.mMotionController.gameObject && rMessage.ID == CombatMessage.MSG_DEFENDER_KILLED && !this.mIsActive)
				{
					Vector3 normalized = (this.mMotionController._Transform.InverseTransformPoint(combatMessage.HitPoint) - Vector3.zero).normalized;
					float num = Vector3.forward.HorizontalAngleTo(normalized, Vector3.up);
					this.mMotionController.ActivateMotion(this, (int)num);
					rMessage.IsHandled = true;
					return;
				}
			}
			else if (rMessage is DamageMessage && rMessage.ID == CombatMessage.MSG_DEFENDER_KILLED)
			{
				this.mMotionController.ActivateMotion(this, 0);
				rMessage.IsHandled = true;
			}
		}

		// Token: 0x1700001D RID: 29
		// (get) Token: 0x06000085 RID: 133 RVA: 0x00004D37 File Offset: 0x00002F37
		public override bool HasAutoGeneratedCode
		{
			get
			{
				return false;
			}
		}

		// Token: 0x1700001E RID: 30
		// (get) Token: 0x06000086 RID: 134 RVA: 0x00004D3C File Offset: 0x00002F3C
		public override bool IsInMotionState
		{
			get
			{
				int animatorStateID = this.mMotionLayer._AnimatorStateID;
				int animatorTransitionID = this.mMotionLayer._AnimatorTransitionID;
				if (animatorTransitionID == 0)
				{
					if (animatorStateID == Death.STATE_Start)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_Idle_PushButton)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_IdlePose)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_Idle_PickUp)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_Sleeping)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_GettingUp)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_LayingDown)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_Death_180)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_Death_0)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_Damaged_0)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_Stunned)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_Cower)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_CowerOut)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_KnockedDown)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_GettingUpBackward)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_DeathPose)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_Frozen)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_PushedBack_Pose)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_PushedBack_Recover)
					{
						return true;
					}
					if (animatorStateID == Death.STATE_PushedBack_Loop)
					{
						return true;
					}
				}
				return animatorTransitionID == Death.TRANS_AnyState_Idle_PushButton || animatorTransitionID == Death.TRANS_EntryState_Idle_PushButton || animatorTransitionID == Death.TRANS_AnyState_Idle_PickUp || animatorTransitionID == Death.TRANS_EntryState_Idle_PickUp || animatorTransitionID == Death.TRANS_AnyState_LayingDown || animatorTransitionID == Death.TRANS_EntryState_LayingDown || animatorTransitionID == Death.TRANS_AnyState_Damaged_0 || animatorTransitionID == Death.TRANS_EntryState_Damaged_0 || animatorTransitionID == Death.TRANS_AnyState_Death_180 || animatorTransitionID == Death.TRANS_EntryState_Death_180 || animatorTransitionID == Death.TRANS_AnyState_Death_0 || animatorTransitionID == Death.TRANS_EntryState_Death_0 || animatorTransitionID == Death.TRANS_AnyState_Stunned || animatorTransitionID == Death.TRANS_EntryState_Stunned || animatorTransitionID == Death.TRANS_AnyState_Cower || animatorTransitionID == Death.TRANS_EntryState_Cower || animatorTransitionID == Death.TRANS_AnyState_KnockedDown || animatorTransitionID == Death.TRANS_EntryState_KnockedDown || animatorTransitionID == Death.TRANS_AnyState_DeathPose || animatorTransitionID == Death.TRANS_EntryState_DeathPose || animatorTransitionID == Death.TRANS_AnyState_Death_180 || animatorTransitionID == Death.TRANS_EntryState_Death_180 || animatorTransitionID == Death.TRANS_AnyState_Frozen || animatorTransitionID == Death.TRANS_EntryState_Frozen || animatorTransitionID == Death.TRANS_AnyState_PushedBack_Pose || animatorTransitionID == Death.TRANS_EntryState_PushedBack_Pose || animatorTransitionID == Death.TRANS_Idle_PushButton_IdlePose || animatorTransitionID == Death.TRANS_Idle_PickUp_IdlePose || animatorTransitionID == Death.TRANS_Sleeping_GettingUp || animatorTransitionID == Death.TRANS_GettingUp_IdlePose || animatorTransitionID == Death.TRANS_LayingDown_Sleeping || animatorTransitionID == Death.TRANS_Damaged_0_IdlePose || animatorTransitionID == Death.TRANS_Stunned_IdlePose || animatorTransitionID == Death.TRANS_Cower_CowerOut || animatorTransitionID == Death.TRANS_CowerOut_IdlePose || animatorTransitionID == Death.TRANS_KnockedDown_GettingUpBackward || animatorTransitionID == Death.TRANS_GettingUpBackward_IdlePose || animatorTransitionID == Death.TRANS_Frozen_IdlePose || animatorTransitionID == Death.TRANS_PushedBack_Pose_PushedBack_Loop || animatorTransitionID == Death.TRANS_PushedBack_Recover_IdlePose || animatorTransitionID == Death.TRANS_PushedBack_Loop_PushedBack_Recover;
			}
		}

		// Token: 0x06000087 RID: 135 RVA: 0x00004FCC File Offset: 0x000031CC
		public override bool IsMotionState(int rStateID)
		{
			return rStateID == Death.STATE_Start || rStateID == Death.STATE_Idle_PushButton || rStateID == Death.STATE_IdlePose || rStateID == Death.STATE_Idle_PickUp || rStateID == Death.STATE_Sleeping || rStateID == Death.STATE_GettingUp || rStateID == Death.STATE_LayingDown || rStateID == Death.STATE_Death_180 || rStateID == Death.STATE_Death_0 || rStateID == Death.STATE_Damaged_0 || rStateID == Death.STATE_Stunned || rStateID == Death.STATE_Cower || rStateID == Death.STATE_CowerOut || rStateID == Death.STATE_KnockedDown || rStateID == Death.STATE_GettingUpBackward || rStateID == Death.STATE_DeathPose || rStateID == Death.STATE_Frozen || rStateID == Death.STATE_PushedBack_Pose || rStateID == Death.STATE_PushedBack_Recover || rStateID == Death.STATE_PushedBack_Loop;
		}

		// Token: 0x06000088 RID: 136 RVA: 0x000050A4 File Offset: 0x000032A4
		public override bool IsMotionState(int rStateID, int rTransitionID)
		{
			if (rTransitionID == 0)
			{
				if (rStateID == Death.STATE_Start)
				{
					return true;
				}
				if (rStateID == Death.STATE_Idle_PushButton)
				{
					return true;
				}
				if (rStateID == Death.STATE_IdlePose)
				{
					return true;
				}
				if (rStateID == Death.STATE_Idle_PickUp)
				{
					return true;
				}
				if (rStateID == Death.STATE_Sleeping)
				{
					return true;
				}
				if (rStateID == Death.STATE_GettingUp)
				{
					return true;
				}
				if (rStateID == Death.STATE_LayingDown)
				{
					return true;
				}
				if (rStateID == Death.STATE_Death_180)
				{
					return true;
				}
				if (rStateID == Death.STATE_Death_0)
				{
					return true;
				}
				if (rStateID == Death.STATE_Damaged_0)
				{
					return true;
				}
				if (rStateID == Death.STATE_Stunned)
				{
					return true;
				}
				if (rStateID == Death.STATE_Cower)
				{
					return true;
				}
				if (rStateID == Death.STATE_CowerOut)
				{
					return true;
				}
				if (rStateID == Death.STATE_KnockedDown)
				{
					return true;
				}
				if (rStateID == Death.STATE_GettingUpBackward)
				{
					return true;
				}
				if (rStateID == Death.STATE_DeathPose)
				{
					return true;
				}
				if (rStateID == Death.STATE_Frozen)
				{
					return true;
				}
				if (rStateID == Death.STATE_PushedBack_Pose)
				{
					return true;
				}
				if (rStateID == Death.STATE_PushedBack_Recover)
				{
					return true;
				}
				if (rStateID == Death.STATE_PushedBack_Loop)
				{
					return true;
				}
			}
			return rTransitionID == Death.TRANS_AnyState_Idle_PushButton || rTransitionID == Death.TRANS_EntryState_Idle_PushButton || rTransitionID == Death.TRANS_AnyState_Idle_PickUp || rTransitionID == Death.TRANS_EntryState_Idle_PickUp || rTransitionID == Death.TRANS_AnyState_LayingDown || rTransitionID == Death.TRANS_EntryState_LayingDown || rTransitionID == Death.TRANS_AnyState_Damaged_0 || rTransitionID == Death.TRANS_EntryState_Damaged_0 || rTransitionID == Death.TRANS_AnyState_Death_180 || rTransitionID == Death.TRANS_EntryState_Death_180 || rTransitionID == Death.TRANS_AnyState_Death_0 || rTransitionID == Death.TRANS_EntryState_Death_0 || rTransitionID == Death.TRANS_AnyState_Stunned || rTransitionID == Death.TRANS_EntryState_Stunned || rTransitionID == Death.TRANS_AnyState_Cower || rTransitionID == Death.TRANS_EntryState_Cower || rTransitionID == Death.TRANS_AnyState_KnockedDown || rTransitionID == Death.TRANS_EntryState_KnockedDown || rTransitionID == Death.TRANS_AnyState_DeathPose || rTransitionID == Death.TRANS_EntryState_DeathPose || rTransitionID == Death.TRANS_AnyState_Death_180 || rTransitionID == Death.TRANS_EntryState_Death_180 || rTransitionID == Death.TRANS_AnyState_Frozen || rTransitionID == Death.TRANS_EntryState_Frozen || rTransitionID == Death.TRANS_AnyState_PushedBack_Pose || rTransitionID == Death.TRANS_EntryState_PushedBack_Pose || rTransitionID == Death.TRANS_Idle_PushButton_IdlePose || rTransitionID == Death.TRANS_Idle_PickUp_IdlePose || rTransitionID == Death.TRANS_Sleeping_GettingUp || rTransitionID == Death.TRANS_GettingUp_IdlePose || rTransitionID == Death.TRANS_LayingDown_Sleeping || rTransitionID == Death.TRANS_Damaged_0_IdlePose || rTransitionID == Death.TRANS_Stunned_IdlePose || rTransitionID == Death.TRANS_Cower_CowerOut || rTransitionID == Death.TRANS_CowerOut_IdlePose || rTransitionID == Death.TRANS_KnockedDown_GettingUpBackward || rTransitionID == Death.TRANS_GettingUpBackward_IdlePose || rTransitionID == Death.TRANS_Frozen_IdlePose || rTransitionID == Death.TRANS_PushedBack_Pose_PushedBack_Loop || rTransitionID == Death.TRANS_PushedBack_Recover_IdlePose || rTransitionID == Death.TRANS_PushedBack_Loop_PushedBack_Recover;
		}

		// Token: 0x06000089 RID: 137 RVA: 0x0000531C File Offset: 0x0000351C
		public override void LoadAnimatorData()
		{
			Death.TRANS_AnyState_Idle_PushButton = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.Idle_PushButton");
			Death.TRANS_EntryState_Idle_PushButton = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.Idle_PushButton");
			Death.TRANS_AnyState_Idle_PickUp = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.Idle_PickUp");
			Death.TRANS_EntryState_Idle_PickUp = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.Idle_PickUp");
			Death.TRANS_AnyState_LayingDown = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.LayingDown");
			Death.TRANS_EntryState_LayingDown = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.LayingDown");
			Death.TRANS_AnyState_Damaged_0 = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.Damaged_0");
			Death.TRANS_EntryState_Damaged_0 = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.Damaged_0");
			Death.TRANS_AnyState_Death_180 = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.Death_180");
			Death.TRANS_EntryState_Death_180 = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.Death_180");
			Death.TRANS_AnyState_Death_0 = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.Death_0");
			Death.TRANS_EntryState_Death_0 = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.Death_0");
			Death.TRANS_AnyState_Stunned = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.Stunned");
			Death.TRANS_EntryState_Stunned = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.Stunned");
			Death.TRANS_AnyState_Cower = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.Cower");
			Death.TRANS_EntryState_Cower = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.Cower");
			Death.TRANS_AnyState_KnockedDown = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.KnockedDown");
			Death.TRANS_EntryState_KnockedDown = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.KnockedDown");
			Death.TRANS_AnyState_DeathPose = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.DeathPose");
			Death.TRANS_EntryState_DeathPose = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.DeathPose");
			Death.TRANS_AnyState_Death_180 = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.Death_180");
			Death.TRANS_EntryState_Death_180 = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.Death_180");
			Death.TRANS_AnyState_Frozen = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.Frozen");
			Death.TRANS_EntryState_Frozen = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.Frozen");
			Death.TRANS_AnyState_PushedBack_Pose = this.mMotionController.AddAnimatorName("AnyState -> Base Layer.Utilities-SM.PushedBack_Pose");
			Death.TRANS_EntryState_PushedBack_Pose = this.mMotionController.AddAnimatorName("Entry -> Base Layer.Utilities-SM.PushedBack_Pose");
			Death.STATE_Start = this.mMotionController.AddAnimatorName("Base Layer.Start");
			Death.STATE_Idle_PushButton = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Idle_PushButton");
			Death.TRANS_Idle_PushButton_IdlePose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Idle_PushButton -> Base Layer.Utilities-SM.IdlePose");
			Death.STATE_IdlePose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.IdlePose");
			Death.STATE_Idle_PickUp = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Idle_PickUp");
			Death.TRANS_Idle_PickUp_IdlePose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Idle_PickUp -> Base Layer.Utilities-SM.IdlePose");
			Death.STATE_Sleeping = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Sleeping");
			Death.TRANS_Sleeping_GettingUp = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Sleeping -> Base Layer.Utilities-SM.GettingUp");
			Death.STATE_GettingUp = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.GettingUp");
			Death.TRANS_GettingUp_IdlePose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.GettingUp -> Base Layer.Utilities-SM.IdlePose");
			Death.STATE_LayingDown = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.LayingDown");
			Death.TRANS_LayingDown_Sleeping = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.LayingDown -> Base Layer.Utilities-SM.Sleeping");
			Death.STATE_Death_180 = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Death_180");
			Death.STATE_Death_0 = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Death_0");
			Death.STATE_Damaged_0 = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Damaged_0");
			Death.TRANS_Damaged_0_IdlePose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Damaged_0 -> Base Layer.Utilities-SM.IdlePose");
			Death.STATE_Stunned = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Stunned");
			Death.TRANS_Stunned_IdlePose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Stunned -> Base Layer.Utilities-SM.IdlePose");
			Death.STATE_Cower = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Cower");
			Death.TRANS_Cower_CowerOut = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Cower -> Base Layer.Utilities-SM.Cower Out");
			Death.STATE_CowerOut = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Cower Out");
			Death.TRANS_CowerOut_IdlePose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Cower Out -> Base Layer.Utilities-SM.IdlePose");
			Death.STATE_KnockedDown = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.KnockedDown");
			Death.TRANS_KnockedDown_GettingUpBackward = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.KnockedDown -> Base Layer.Utilities-SM.GettingUpBackward");
			Death.STATE_GettingUpBackward = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.GettingUpBackward");
			Death.TRANS_GettingUpBackward_IdlePose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.GettingUpBackward -> Base Layer.Utilities-SM.IdlePose");
			Death.STATE_DeathPose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.DeathPose");
			Death.STATE_Frozen = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Frozen");
			Death.TRANS_Frozen_IdlePose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.Frozen -> Base Layer.Utilities-SM.IdlePose");
			Death.STATE_PushedBack_Pose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.PushedBack_Pose");
			Death.TRANS_PushedBack_Pose_PushedBack_Loop = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.PushedBack_Pose -> Base Layer.Utilities-SM.PushedBack_Loop");
			Death.STATE_PushedBack_Recover = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.PushedBack_Recover");
			Death.TRANS_PushedBack_Recover_IdlePose = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.PushedBack_Recover -> Base Layer.Utilities-SM.IdlePose");
			Death.STATE_PushedBack_Loop = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.PushedBack_Loop");
			Death.TRANS_PushedBack_Loop_PushedBack_Recover = this.mMotionController.AddAnimatorName("Base Layer.Utilities-SM.PushedBack_Loop -> Base Layer.Utilities-SM.PushedBack_Recover");
		}

		// Token: 0x04000065 RID: 101
		public const int PHASE_UNKNOWN = 0;

		// Token: 0x04000066 RID: 102
		public const int PHASE_START = 1840;

		// Token: 0x04000067 RID: 103
		private bool mIsClean;

		// Token: 0x04000068 RID: 104
		public static int STATE_Start = -1;

		// Token: 0x04000069 RID: 105
		public static int STATE_Idle_PushButton = -1;

		// Token: 0x0400006A RID: 106
		public static int STATE_IdlePose = -1;

		// Token: 0x0400006B RID: 107
		public static int STATE_Idle_PickUp = -1;

		// Token: 0x0400006C RID: 108
		public static int STATE_Sleeping = -1;

		// Token: 0x0400006D RID: 109
		public static int STATE_GettingUp = -1;

		// Token: 0x0400006E RID: 110
		public static int STATE_LayingDown = -1;

		// Token: 0x0400006F RID: 111
		public static int STATE_Death_180 = -1;

		// Token: 0x04000070 RID: 112
		public static int STATE_Death_0 = -1;

		// Token: 0x04000071 RID: 113
		public static int STATE_Damaged_0 = -1;

		// Token: 0x04000072 RID: 114
		public static int STATE_Stunned = -1;

		// Token: 0x04000073 RID: 115
		public static int STATE_Cower = -1;

		// Token: 0x04000074 RID: 116
		public static int STATE_CowerOut = -1;

		// Token: 0x04000075 RID: 117
		public static int STATE_KnockedDown = -1;

		// Token: 0x04000076 RID: 118
		public static int STATE_GettingUpBackward = -1;

		// Token: 0x04000077 RID: 119
		public static int STATE_DeathPose = -1;

		// Token: 0x04000078 RID: 120
		public static int STATE_Frozen = -1;

		// Token: 0x04000079 RID: 121
		public static int STATE_PushedBack_Pose = -1;

		// Token: 0x0400007A RID: 122
		public static int STATE_PushedBack_Recover = -1;

		// Token: 0x0400007B RID: 123
		public static int STATE_PushedBack_Loop = -1;

		// Token: 0x0400007C RID: 124
		public static int TRANS_AnyState_Idle_PushButton = -1;

		// Token: 0x0400007D RID: 125
		public static int TRANS_EntryState_Idle_PushButton = -1;

		// Token: 0x0400007E RID: 126
		public static int TRANS_AnyState_Idle_PickUp = -1;

		// Token: 0x0400007F RID: 127
		public static int TRANS_EntryState_Idle_PickUp = -1;

		// Token: 0x04000080 RID: 128
		public static int TRANS_AnyState_LayingDown = -1;

		// Token: 0x04000081 RID: 129
		public static int TRANS_EntryState_LayingDown = -1;

		// Token: 0x04000082 RID: 130
		public static int TRANS_AnyState_Damaged_0 = -1;

		// Token: 0x04000083 RID: 131
		public static int TRANS_EntryState_Damaged_0 = -1;

		// Token: 0x04000084 RID: 132
		public static int TRANS_AnyState_Death_180 = -1;

		// Token: 0x04000085 RID: 133
		public static int TRANS_EntryState_Death_180 = -1;

		// Token: 0x04000086 RID: 134
		public static int TRANS_AnyState_Death_0 = -1;

		// Token: 0x04000087 RID: 135
		public static int TRANS_EntryState_Death_0 = -1;

		// Token: 0x04000088 RID: 136
		public static int TRANS_AnyState_Stunned = -1;

		// Token: 0x04000089 RID: 137
		public static int TRANS_EntryState_Stunned = -1;

		// Token: 0x0400008A RID: 138
		public static int TRANS_AnyState_Cower = -1;

		// Token: 0x0400008B RID: 139
		public static int TRANS_EntryState_Cower = -1;

		// Token: 0x0400008C RID: 140
		public static int TRANS_AnyState_KnockedDown = -1;

		// Token: 0x0400008D RID: 141
		public static int TRANS_EntryState_KnockedDown = -1;

		// Token: 0x0400008E RID: 142
		public static int TRANS_AnyState_DeathPose = -1;

		// Token: 0x0400008F RID: 143
		public static int TRANS_EntryState_DeathPose = -1;

		// Token: 0x04000090 RID: 144
		public static int TRANS_AnyState_Frozen = -1;

		// Token: 0x04000091 RID: 145
		public static int TRANS_EntryState_Frozen = -1;

		// Token: 0x04000092 RID: 146
		public static int TRANS_AnyState_PushedBack_Pose = -1;

		// Token: 0x04000093 RID: 147
		public static int TRANS_EntryState_PushedBack_Pose = -1;

		// Token: 0x04000094 RID: 148
		public static int TRANS_Idle_PushButton_IdlePose = -1;

		// Token: 0x04000095 RID: 149
		public static int TRANS_Idle_PickUp_IdlePose = -1;

		// Token: 0x04000096 RID: 150
		public static int TRANS_Sleeping_GettingUp = -1;

		// Token: 0x04000097 RID: 151
		public static int TRANS_GettingUp_IdlePose = -1;

		// Token: 0x04000098 RID: 152
		public static int TRANS_LayingDown_Sleeping = -1;

		// Token: 0x04000099 RID: 153
		public static int TRANS_Damaged_0_IdlePose = -1;

		// Token: 0x0400009A RID: 154
		public static int TRANS_Stunned_IdlePose = -1;

		// Token: 0x0400009B RID: 155
		public static int TRANS_Cower_CowerOut = -1;

		// Token: 0x0400009C RID: 156
		public static int TRANS_CowerOut_IdlePose = -1;

		// Token: 0x0400009D RID: 157
		public static int TRANS_KnockedDown_GettingUpBackward = -1;

		// Token: 0x0400009E RID: 158
		public static int TRANS_GettingUpBackward_IdlePose = -1;

		// Token: 0x0400009F RID: 159
		public static int TRANS_Frozen_IdlePose = -1;

		// Token: 0x040000A0 RID: 160
		public static int TRANS_PushedBack_Pose_PushedBack_Loop = -1;

		// Token: 0x040000A1 RID: 161
		public static int TRANS_PushedBack_Recover_IdlePose = -1;

		// Token: 0x040000A2 RID: 162
		public static int TRANS_PushedBack_Loop_PushedBack_Recover = -1;
	}
}
